---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/resl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - 127.0.0.1:6050
      - 127.0.0.1:6051
      - 127.0.0.1:6052
      - 127.0.0.1:6053
      - 127.0.0.1:6054

  - &OrgRegulatory
    Name: OrgRegulatoryMSP
    ID: OrgRegulatoryMSP
    MSPDir: crypto-config/peerOrganizations/regulatory.resl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgRegulatoryMSP.admin', 'OrgRegulatoryMSP.peer', 'OrgRegulatoryMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgRegulatoryMSP.admin', 'OrgRegulatoryMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgRegulatoryMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgRegulatoryMSP.peer')"
    AnchorPeers:
      - Host: 127.0.0.1
        Port: 7051

  - &OrgBrokerage
    Name: OrgBrokerageMSP
    ID: OrgBrokerageMSP
    MSPDir: crypto-config/peerOrganizations/brokerage.resl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgBrokerageMSP.admin', 'OrgBrokerageMSP.peer', 'OrgBrokerageMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgBrokerageMSP.admin', 'OrgBrokerageMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgBrokerageMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgBrokerageMSP.peer')"
    AnchorPeers:
      - Host: 127.0.0.1
        Port: 7052

  - &OrgLenders
    Name: OrgLendersMSP
    ID: OrgLendersMSP
    MSPDir: crypto-config/peerOrganizations/lenders.resl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgLendersMSP.admin', 'OrgLendersMSP.peer', 'OrgLendersMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgLendersMSP.admin', 'OrgLendersMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgLendersMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgLendersMSP.peer')"
    AnchorPeers:
      - Host: 127.0.0.1
        Port: 7053

  - &OrgTitle
    Name: OrgTitleMSP
    ID: OrgTitleMSP
    MSPDir: crypto-config/peerOrganizations/title.resl.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrgTitleMSP.admin', 'OrgTitleMSP.peer', 'OrgTitleMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('OrgTitleMSP.admin', 'OrgTitleMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('OrgTitleMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrgTitleMSP.peer')"
    AnchorPeers:
      - Host: 127.0.0.1
        Port: 7054

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: Signature
      Rule: "OR('OrgRegulatoryMSP.peer', 'OrgBrokerageMSP.peer', 'OrgLendersMSP.peer', 'OrgTitleMSP.peer')"
    Endorsement:
      Type: Signature
      Rule: "OR('OrgRegulatoryMSP.peer', 'OrgBrokerageMSP.peer', 'OrgLendersMSP.peer', 'OrgTitleMSP.peer')"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  RealEstateOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      RealEstateConsortium:
        Organizations:
          - *OrgRegulatory
          - *OrgBrokerage
          - *OrgLenders
          - *OrgTitle

  RealEstateChannel:
    Consortium: RealEstateConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrgRegulatory
        - *OrgBrokerage
        - *OrgLenders
        - *OrgTitle
      Capabilities:
        <<: *ApplicationCapabilities
